name: .NET Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Solution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Add .NET tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory coverage

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'coverage/*/coverage.cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Install Coveralls.net Tool
      run: dotnet tool install --global coveralls.net

    - name: Find Coverage File
      id: find_file
      run: echo "COVERAGE_FILE=$(find $(pwd)/coverage -name coverage.cobertura.xml)" >> $GITHUB_ENV

    - name: Debug Information
      run: |
        echo "Working Directory: $(pwd)"
        echo "Listing Coverage Directory:"
        ls -al $(pwd)/coverage
        echo "Coverage File: ${{ env.COVERAGE_FILE }}"

    - name: Run Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        echo "Running Coveralls with coverage file: ${{ env.COVERAGE_FILE }}"
        csmacnz.Coveralls --reportgenerator -i "${{ env.COVERAGE_FILE }}" --repoToken $COVERALLS_REPO_TOKEN || echo "Coveralls failed"
