name: Build-deploy pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build-push image
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dotnet build
        run: docker build

      - name: Run tests
        run: dotnet test -c Release --collect:"XPlat Code Coverage"

      - name: Write to Job Summary unit tests results
        run: cat tests-results/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: tests-results/Cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "40 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          recreate: true
          path: code-coverage-results.md
